######################################################################
# Automatically generated by qmake (3.0) mer. avr. 1 14:25:40 2015
######################################################################

TEMPLATE = app
TARGET = FollowAndDrop
INCLUDEPATH += .

# Input
HEADERS += mainwindow.h \
    sphere.h
FORMS += mainwindow.ui
SOURCES += main.cpp mainwindow.cpp \
    sphere.cpp
QT += widgets
LIBS = -lglut -lGLU \
